AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

# Methods returning hashes shouldn't be taken care of
Metrics/MethodLength:
  CountAsOne: "hash"

Metrics/BlockLength:
  Exclude:
    - "**/*"

Metrics/ClassLength:
  Max: 200
