# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'debug', '>= 1.0.0'
  gem 'rspec', '~> 3.13.2'
  gem 'rubocop', '~> 1.86.1'
  gem 'rubocop-rspec', '~> 3.9.0'
end
